name: CI/CD to AWS AppRunner with GitHub Actions
on:
  push:
    branches: [development] # Trigger workflow on git push to main branch
  workflow_dispatch: # Allow manual invocation of the workflow
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Installing dependencies
        id: deployment-stack-exists
        run: |
          npm run install
          npm run build

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Check if web bucket deployment exists
      #   id: deployment-stack-exists
      #   run: |
      #     stack_name="finance-deployment-stack"
      #     if aws cloudformation describe-stacks --stack-name $stack_name --output json; then
      #       echo "Stack exists."
      #     else
      #       echo "Stack does not exist. Creating deployment stack..."
      #       aws cloudformation create-stack \
      #         --stack-name $stack_name \
      #         --template-body file://cf/deployment.yaml \
      #         --capabilities CAPABILITY_NAMED_IAM
      #       aws cloudformation wait stack-create-complete --stack-name $stack_name
      #     fi
      #   continue-on-error: false


