name: CI/CD to AWS AppRunner with GitHub Actions
on:
  push:
    branches: [development] # Trigger workflow on git push to main branch
  workflow_dispatch: # Allow manual invocation of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Installing dependencies and Generating binaries
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_ENDPOINT: ${{ secrets.REACT_APP_ENDPOINT }}
          REACT_APP_STAGE: ${{ secrets.REACT_APP_STAGE }}
        run: |
          npm install
          npm run build

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check web bucket for deployment
        id: deployment-stack-exists
        run: |
          aws s3 cp ./build s3://static-website-finance-dev/ --recursive

